### ISSUE TITLE
cannot open display: :1

### ISSUE THREAD

**Issue by Hammer2900** [trustable-code/NiGui#30] opened 2019-01-18 07:25 UTC
compile standard example on Ubuntu 18.04.1 LTS and get error, cannot open display: :1 , how can i fix it ?cannot open display: :1

**Comment by trustable-code** [comment] 2019-01-19 15:41
I tried to reproduce this, but wasn't successful.
It works for me in a fresh installation of Ubuntu 18.04.1 LTS and with Nim 0.19.2
![screenshot_2019-01-19_16-38-05](https://user-images.githubusercontent.com/8593614/51428851-efccc000-1c08-11e9-94b8-79f56f020766.png)

I have no idea, where the error message comes from. NiGui does nothing related to "display".

**Comment by trustable-code** [comment] 2019-01-19 16:34
@Yardanico Can you please explain this more? Why does NiGui need Xorg? NiGui uses the higher level Gtk.

**Comment by 0xACE** [comment] 2019-02-19 15:26
@trustable-code I'm not familiar with wayland yet, but my best guess is that gtk3 is compiled with dependencies from xorg/X11.

Essentially Xorg or uses the `DISPLAY` environment variable to know which xorg instance it should render on.

```
$ DISPLAY=:0 gvim & # this client will be visible in session :0
$ DISPLAY=:1 gvim # this client will be visible in session :1
```

And in this case: gtk is trying to connect to a `DISPLAY` which doesn't exist or he lacks authorization to use.

Maybe it is possible to compile gtk3 without Xorg dependencies, but then the reverse problem would happen for Xorg users and as of yet I'm not familiar with a Wayland to Xorg proxy, but I have heard of existing implementations of Xorg to Wayland proxies.

I hope this helps :-)

**Comment by trustable-code** [comment] 2019-03-21 06:39
This is not an issue of NiGui. Closing.

**Closed by trustable-code** 2019-03-21 06:39 UTC
